# .github/workflows/test-coverage.yml

name: Run Test Coverage

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore

    - name: Clean
      working-directory: ./src
      run: dotnet clean

    - name: Build
      working-directory: ./src
      run: dotnet build --no-restore --configuration Release /p:BuildInParallel=false

    - name: Run tests with coverage
      run: |
        dotnet test ./tests/MudX.UnitTests/MudX.UnitTests.csproj \
        -c Release --no-build --no-restore --blame-hang --blame-hang-timeout 60s --verbosity normal \
        /p:Exclude="[MudX.DependsOn]*,[MudX.UnitTests.Viewer]*" \
        /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput='./TestResults/coverage.xml'
        
    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./tests/MudX.UnitTests/TestResults/coverage.xml
        format: cobertura

    # Optional: Upload coverage file for debugging
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./tests/MudX.UnitTests/TestResults/coverage.xml
